version: '3.8'

services:
  backend:
    container_name: ml-stack2-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

  #frontend:
  #  container_name: ml-stack2-frontend
  #  build:
  #    context: ./frontend
  #    dockerfile: Dockerfile
  #  ports:
  #    - "8501:8080"
  #  depends_on:
  #    - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example_db
    ports:
      - "5434:5432"
